development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDISTOGO_URL") { "redis://redistogo:4189ab11b8cdf23a94807ae5479a7970@soapfish.redistogo.com:10180/" } %>
  channel_prefix: construaventura_production
